version: '{build}-{branch}'
image: Visual Studio 2022

clone_depth: 1

init:
- ps: |
    function craft() {
        & C:\python310\python.exe "C:\CraftMaster\CraftMaster\CraftMaster.py" --config "$env:APPVEYOR_BUILD_FOLDER\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $env:TARGET -c $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --depth=1 https://invent.kde.org/packaging/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    & cmd /C "git clone https://gitlab.freedesktop.org/poppler/test.git $env:APPVEYOR_BUILD_FOLDER/../test 2>&1"
    craft craft
    craft --install-deps poppler

build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER poppler

test_script:
- ps: |
     craft -v --src-dir $env:APPVEYOR_BUILD_FOLDER --test poppler
     cd $env:APPVEYOR_BUILD_FOLDER && qt6/tests/check_qt6_signature_basics.exe


environment:
    global:
    - GPGME_DEBUG: 8    
    matrix:
    - TARGET: windows-mingw_64-gcc
    - TARGET: windows-msvc2022_64-cl
